version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: erasgames_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: erasgames
    ports:
      - '5430:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
